# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AssemArms.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import*
import itertools
import pyfirmata
import time 
import pandas # Data management on the .csv file 
AnalogReadA1 = 0 

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1412, 880)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.dial = QtWidgets.QDial(self.centralwidget)
        self.dial.setGeometry(QtCore.QRect(70, 230, 50, 64))
        self.dial.setObjectName("dial")
        self.dial_2 = QtWidgets.QDial(self.centralwidget)
        self.dial_2.setGeometry(QtCore.QRect(140, 230, 50, 64))
        self.dial_2.setObjectName("dial_2")
        self.dial_3 = QtWidgets.QDial(self.centralwidget)
        self.dial_3.setGeometry(QtCore.QRect(220, 230, 50, 64))
        self.dial_3.setObjectName("dial_3")
        self.dial_4 = QtWidgets.QDial(self.centralwidget)
        self.dial_4.setGeometry(QtCore.QRect(70, 300, 50, 64))
        self.dial_4.setObjectName("dial_4")
        self.horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider.setGeometry(QtCore.QRect(70, 390, 341, 16))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.horizontalSlider_2 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_2.setGeometry(QtCore.QRect(70, 450, 331, 16))
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 200, 41, 17))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(130, 200, 67, 17))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(230, 200, 51, 17))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(60, 290, 111, 17))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(70, 360, 181, 17))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(70, 420, 121, 17))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(60, 10, 131, 17))
        self.label_7.setObjectName("label_7")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(170, 560, 101, 21))
        self.textEdit.setObjectName("textEdit")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(70, 590, 67, 17))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(70, 620, 67, 17))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(46, 650, 111, 20))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(70, 560, 67, 17))
        self.label_11.setObjectName("label_11")
        self.textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_2.setGeometry(QtCore.QRect(170, 590, 101, 21))
        self.textEdit_2.setObjectName("textEdit_2")
        self.textEdit_3 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_3.setGeometry(QtCore.QRect(170, 620, 101, 21))
        self.textEdit_3.setObjectName("textEdit_3")
        self.textEdit_4 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_4.setGeometry(QtCore.QRect(170, 650, 101, 21))
        self.textEdit_4.setObjectName("textEdit_4")
        self.textEdit_5 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_5.setGeometry(QtCore.QRect(170, 680, 101, 21))
        self.textEdit_5.setObjectName("textEdit_5")
        self.textEdit_6 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_6.setGeometry(QtCore.QRect(170, 710, 101, 21))
        self.textEdit_6.setObjectName("textEdit_6")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(40, 680, 111, 20))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(40, 710, 121, 20))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(70, 520, 301, 17))
        self.label_14.setObjectName("label_14")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(60, 70, 101, 25))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(60, 110, 89, 25))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(60, 150, 89, 25))
        self.pushButton_3.setObjectName("pushButton_3")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(190, 70, 341, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.progressBar_2 = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar_2.setGeometry(QtCore.QRect(190, 110, 341, 23))
        self.progressBar_2.setProperty("value", 24)
        self.progressBar_2.setObjectName("progressBar_2")
        self.progressBar_3 = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar_3.setGeometry(QtCore.QRect(190, 150, 341, 23))
        self.progressBar_3.setProperty("value", 24)
        self.progressBar_3.setObjectName("progressBar_3")
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        self.tableView.setGeometry(QtCore.QRect(540, 30, 411, 781))
        self.tableView.setObjectName("tableView")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(660, 10, 181, 17))
        self.label_15.setObjectName("label_15")
        self.tableView_2 = QtWidgets.QTableView(self.centralwidget)
        self.tableView_2.setGeometry(QtCore.QRect(970, 30, 411, 781))
        self.tableView_2.setObjectName("tableView_2")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(1050, 10, 171, 17))
        self.label_16.setObjectName("label_16")
        self.verticalScrollBar = QtWidgets.QScrollBar(self.centralwidget)
        self.verticalScrollBar.setGeometry(QtCore.QRect(950, 30, 16, 781))
        self.verticalScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar.setObjectName("verticalScrollBar")
        self.verticalScrollBar_2 = QtWidgets.QScrollBar(self.centralwidget)
        self.verticalScrollBar_2.setGeometry(QtCore.QRect(1380, 30, 16, 781))
        self.verticalScrollBar_2.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar_2.setObjectName("verticalScrollBar_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1412, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuControl_finger_setting = QtWidgets.QMenu(self.menubar)
        self.menuControl_finger_setting.setObjectName("menuControl_finger_setting")
        self.menuhelp = QtWidgets.QMenu(self.menubar)
        self.menuhelp.setObjectName("menuhelp")
        self.menuIoT_net = QtWidgets.QMenu(self.menubar)
        self.menuIoT_net.setObjectName("menuIoT_net")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionsave = QtWidgets.QAction(MainWindow)
        self.actionsave.setObjectName("actionsave")
        self.actionsave_as = QtWidgets.QAction(MainWindow)
        self.actionsave_as.setObjectName("actionsave_as")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionconnect = QtWidgets.QAction(MainWindow)
        self.actionconnect.setObjectName("actionconnect")
        self.actionsetting_network = QtWidgets.QAction(MainWindow)
        self.actionsetting_network.setObjectName("actionsetting_network")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionsave)
        self.menuFile.addAction(self.actionsave_as)
        self.menuFile.addAction(self.actionQuit)
        self.menuIoT_net.addAction(self.actionconnect)
        self.menuIoT_net.addAction(self.actionsetting_network)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuControl_finger_setting.menuAction())
        self.menubar.addAction(self.menuIoT_net.menuAction())
        self.menubar.addAction(self.menuhelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
           # Button for geenerating file and Motion 
        self.pushButton.clicked.connect(self.Functioningcontrol)
        self.pushButton_2.clicked.connect(self.AnalogRead)
        self.pushButton_3.clicked.connect(self.ProcessingMotion)
          # Dial Setting function and knob positioning control 
        self.dial.setMinimum(0)
        self.dial.setMaximum(100)
        self.dial.setValue(45)
        self.dial.valueChanged.connect(self.Knobcontrol)
          # Dial2 Settings 
         #self.AnalogRead 
        
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Assem Arms factory controller"))
        self.label.setText(_translate("MainWindow", "Base"))
        self.label_2.setText(_translate("MainWindow", "Shoulder"))
        self.label_3.setText(_translate("MainWindow", "Elbow"))
        self.label_4.setText(_translate("MainWindow", "Rotation finger"))
        self.label_5.setText(_translate("MainWindow", "Hydraulic Linear actuator"))
        self.label_6.setText(_translate("MainWindow", "Gripper actuators "))
        self.label_7.setText(_translate("MainWindow", "Motion generator"))
        self.label_8.setText(_translate("MainWindow", "Shoulder"))
        self.label_9.setText(_translate("MainWindow", "Elbow"))
        self.label_10.setText(_translate("MainWindow", "Rotation finger"))
        self.label_11.setText(_translate("MainWindow", "Base"))
        self.label_12.setText(_translate("MainWindow", "Hydraulic Linear"))
        self.label_13.setText(_translate("MainWindow", "Gripper actuators "))
        self.label_14.setText(_translate("MainWindow", "Key data input with know specific function "))
        self.pushButton.setText(_translate("MainWindow", "Generate file "))
        self.pushButton_2.setText(_translate("MainWindow", "Test motion"))
        self.pushButton_3.setText(_translate("MainWindow", "Processing "))
        self.label_15.setText(_translate("MainWindow", "Components Process list "))
        self.label_16.setText(_translate("MainWindow", "Process check scheme "))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.menuControl_finger_setting.setTitle(_translate("MainWindow", "Control finger setting"))
        self.menuhelp.setTitle(_translate("MainWindow", "help "))
        self.menuIoT_net.setTitle(_translate("MainWindow", "IoT net "))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionsave.setText(_translate("MainWindow", "save "))
        self.actionsave_as.setText(_translate("MainWindow", "save as "))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionconnect.setText(_translate("MainWindow", "connect"))
        self.actionsetting_network.setText(_translate("MainWindow", "setting network "))

    def Quitui(self): 
        sys.exit() 
    def Functioningcontrol(self): 
        file = open("RoboticsScrypt.csv","w+")  # wtite the file name after button 
        print("Generating....") 
        count = 0 
        while count < 100: 
            count +=1 
            time.sleep(0.2) 
            self.progressBar.setValue(count)
            if count == 100: 
                 print("Generating complete !")
    def TestMotiondrive(self): 
        file = open("RoboticsScrypt.csv","r")   # read the file to replay the resent motion 
    def ProcessingMotion(self): 
        file = open("RoboticsScrypt.csv","a+")  # Add the full processing constance processing scrypt 
    
    def Knobcontrol(self):
        print("Dial value = %i" % (self.dial.value()))
        blink.write(self.dial.value()/10)  # Hardware linking control brigtness of the LED test 
    def AnalogRead(self): 
        for _ in itertools.count():
             AnalogReadA1 = hardware.analog[0].read()
             self.progressBar_2.setValue(AnalogReadA1*500) 
             print(AnalogReadA1)
if __name__ == "__main__":
    import sys
    import os 
    
    try: 
      hardware = pyfirmata.ArduinoMega('/dev/ttyACM0')
      print("Hardware robotics assembly line connected successfully !")        
    except: 
      print("Hardware connection fail please reconnect and check connection port !")
    it = pyfirmata.util.Iterator(hardware)
    it.start() 
    blink = hardware.get_pin('d:13:p')
    hardware.analog[0].enable_reporting()
    #AnalogReadA1 = hardware.analog[0].read()    
    blink.write(0)
    time.sleep(0.1)
    for i in range(0,10):
       blink.write(i)
       time.sleep(0.2)
    time.sleep(0.1)   
    for i in range(0,10,-1):
       blink.write(i)
       time.sleep(0.2)
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
while True: 
    #blink = hardware.get_pin('d:13:p')
    #blink.write(0)
   # AnalogReadA1 = hardware.analog[0].read()     
    for i in range(0,10):
       blink.write(i)
       time.sleep(0.8)
       print(i)
    time.sleep(0.5)   
    for i in range(0,10,-1):
       blink.write(i)
       time.sleep(0.8)
       print(i)
    time.sleep(0.5)   